# Stub for maya.colorManagementUtilities - reflected from Maya 2024

from typing import Any

cmds: Any

def setViewTransform(editor, optionMenuPath, cmdName): ...

def syncExposureField(editor, floatFieldPath, cmdName): ...

def syncGammaField(editor, floatFieldPath, cmdName): ...

def toggleCM(editor, buttonPath, cmdName): ...

def updateExposure(editor, floatFieldPath, cmdName): ...

def updateGamma(editor, floatFieldPath, cmdName): ...

